# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.run_details import RunDetails  # noqa: E501
from giteapy.rest import ApiException


class TestRunDetails(unittest.TestCase):
    """RunDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunDetails(self):
        """Test RunDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.run_details.RunDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
