# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.25.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.apply_diff_patch_file_options import ApplyDiffPatchFileOptions  # noqa: E501
from giteapy.rest import ApiException


class TestApplyDiffPatchFileOptions(unittest.TestCase):
    """ApplyDiffPatchFileOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplyDiffPatchFileOptions(self):
        """Test ApplyDiffPatchFileOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.apply_diff_patch_file_options.ApplyDiffPatchFileOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
