# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.25.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.rename_org_option import RenameOrgOption  # noqa: E501
from giteapy.rest import ApiException


class TestRenameOrgOption(unittest.TestCase):
    """RenameOrgOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenameOrgOption(self):
        """Test RenameOrgOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.rename_org_option.RenameOrgOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
