# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.25.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.action_workflow_step import ActionWorkflowStep  # noqa: E501
from giteapy.rest import ApiException


class TestActionWorkflowStep(unittest.TestCase):
    """ActionWorkflowStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionWorkflowStep(self):
        """Test ActionWorkflowStep"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.action_workflow_step.ActionWorkflowStep()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
