# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class AccessToken(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'datetime',
        'id': 'int',
        'last_used_at': 'datetime',
        'name': 'str',
        'scopes': 'list[str]',
        'sha1': 'str',
        'token_last_eight': 'str'
    }

    attribute_map = {
        'created_at': 'created_at',
        'id': 'id',
        'last_used_at': 'last_used_at',
        'name': 'name',
        'scopes': 'scopes',
        'sha1': 'sha1',
        'token_last_eight': 'token_last_eight'
    }

    def __init__(self, created_at=None, id=None, last_used_at=None, name=None, scopes=None, sha1=None, token_last_eight=None, _configuration=None):  # noqa: E501
        """AccessToken - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._created_at = None
        self._id = None
        self._last_used_at = None
        self._name = None
        self._scopes = None
        self._sha1 = None
        self._token_last_eight = None
        self.discriminator = None

        if created_at is not None:
            self.created_at = created_at
        if id is not None:
            self.id = id
        if last_used_at is not None:
            self.last_used_at = last_used_at
        if name is not None:
            self.name = name
        if scopes is not None:
            self.scopes = scopes
        if sha1 is not None:
            self.sha1 = sha1
        if token_last_eight is not None:
            self.token_last_eight = token_last_eight

    @property
    def created_at(self):
        """Gets the created_at of this AccessToken.  # noqa: E501

        The timestamp when the token was created  # noqa: E501

        :return: The created_at of this AccessToken.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this AccessToken.

        The timestamp when the token was created  # noqa: E501

        :param created_at: The created_at of this AccessToken.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def id(self):
        """Gets the id of this AccessToken.  # noqa: E501

        The unique identifier of the access token  # noqa: E501

        :return: The id of this AccessToken.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AccessToken.

        The unique identifier of the access token  # noqa: E501

        :param id: The id of this AccessToken.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def last_used_at(self):
        """Gets the last_used_at of this AccessToken.  # noqa: E501

        The timestamp when the token was last used  # noqa: E501

        :return: The last_used_at of this AccessToken.  # noqa: E501
        :rtype: datetime
        """
        return self._last_used_at

    @last_used_at.setter
    def last_used_at(self, last_used_at):
        """Sets the last_used_at of this AccessToken.

        The timestamp when the token was last used  # noqa: E501

        :param last_used_at: The last_used_at of this AccessToken.  # noqa: E501
        :type: datetime
        """

        self._last_used_at = last_used_at

    @property
    def name(self):
        """Gets the name of this AccessToken.  # noqa: E501

        The name of the access token  # noqa: E501

        :return: The name of this AccessToken.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AccessToken.

        The name of the access token  # noqa: E501

        :param name: The name of this AccessToken.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def scopes(self):
        """Gets the scopes of this AccessToken.  # noqa: E501

        The scopes granted to this access token  # noqa: E501

        :return: The scopes of this AccessToken.  # noqa: E501
        :rtype: list[str]
        """
        return self._scopes

    @scopes.setter
    def scopes(self, scopes):
        """Sets the scopes of this AccessToken.

        The scopes granted to this access token  # noqa: E501

        :param scopes: The scopes of this AccessToken.  # noqa: E501
        :type: list[str]
        """

        self._scopes = scopes

    @property
    def sha1(self):
        """Gets the sha1 of this AccessToken.  # noqa: E501

        The SHA1 hash of the access token  # noqa: E501

        :return: The sha1 of this AccessToken.  # noqa: E501
        :rtype: str
        """
        return self._sha1

    @sha1.setter
    def sha1(self, sha1):
        """Sets the sha1 of this AccessToken.

        The SHA1 hash of the access token  # noqa: E501

        :param sha1: The sha1 of this AccessToken.  # noqa: E501
        :type: str
        """

        self._sha1 = sha1

    @property
    def token_last_eight(self):
        """Gets the token_last_eight of this AccessToken.  # noqa: E501

        The last eight characters of the token  # noqa: E501

        :return: The token_last_eight of this AccessToken.  # noqa: E501
        :rtype: str
        """
        return self._token_last_eight

    @token_last_eight.setter
    def token_last_eight(self, token_last_eight):
        """Sets the token_last_eight of this AccessToken.

        The last eight characters of the token  # noqa: E501

        :param token_last_eight: The token_last_eight of this AccessToken.  # noqa: E501
        :type: str
        """

        self._token_last_eight = token_last_eight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccessToken, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessToken):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AccessToken):
            return True

        return self.to_dict() != other.to_dict()
