# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class ActionWorkflow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'badge_url': 'str',
        'created_at': 'datetime',
        'deleted_at': 'datetime',
        'html_url': 'str',
        'id': 'str',
        'name': 'str',
        'path': 'str',
        'state': 'str',
        'updated_at': 'datetime',
        'url': 'str'
    }

    attribute_map = {
        'badge_url': 'badge_url',
        'created_at': 'created_at',
        'deleted_at': 'deleted_at',
        'html_url': 'html_url',
        'id': 'id',
        'name': 'name',
        'path': 'path',
        'state': 'state',
        'updated_at': 'updated_at',
        'url': 'url'
    }

    def __init__(self, badge_url=None, created_at=None, deleted_at=None, html_url=None, id=None, name=None, path=None, state=None, updated_at=None, url=None, _configuration=None):  # noqa: E501
        """ActionWorkflow - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._badge_url = None
        self._created_at = None
        self._deleted_at = None
        self._html_url = None
        self._id = None
        self._name = None
        self._path = None
        self._state = None
        self._updated_at = None
        self._url = None
        self.discriminator = None

        if badge_url is not None:
            self.badge_url = badge_url
        if created_at is not None:
            self.created_at = created_at
        if deleted_at is not None:
            self.deleted_at = deleted_at
        if html_url is not None:
            self.html_url = html_url
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if path is not None:
            self.path = path
        if state is not None:
            self.state = state
        if updated_at is not None:
            self.updated_at = updated_at
        if url is not None:
            self.url = url

    @property
    def badge_url(self):
        """Gets the badge_url of this ActionWorkflow.  # noqa: E501

        BadgeURL is the URL for the workflow badge  # noqa: E501

        :return: The badge_url of this ActionWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._badge_url

    @badge_url.setter
    def badge_url(self, badge_url):
        """Sets the badge_url of this ActionWorkflow.

        BadgeURL is the URL for the workflow badge  # noqa: E501

        :param badge_url: The badge_url of this ActionWorkflow.  # noqa: E501
        :type: str
        """

        self._badge_url = badge_url

    @property
    def created_at(self):
        """Gets the created_at of this ActionWorkflow.  # noqa: E501


        :return: The created_at of this ActionWorkflow.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ActionWorkflow.


        :param created_at: The created_at of this ActionWorkflow.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def deleted_at(self):
        """Gets the deleted_at of this ActionWorkflow.  # noqa: E501


        :return: The deleted_at of this ActionWorkflow.  # noqa: E501
        :rtype: datetime
        """
        return self._deleted_at

    @deleted_at.setter
    def deleted_at(self, deleted_at):
        """Sets the deleted_at of this ActionWorkflow.


        :param deleted_at: The deleted_at of this ActionWorkflow.  # noqa: E501
        :type: datetime
        """

        self._deleted_at = deleted_at

    @property
    def html_url(self):
        """Gets the html_url of this ActionWorkflow.  # noqa: E501

        HTMLURL is the web URL for viewing the workflow  # noqa: E501

        :return: The html_url of this ActionWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._html_url

    @html_url.setter
    def html_url(self, html_url):
        """Sets the html_url of this ActionWorkflow.

        HTMLURL is the web URL for viewing the workflow  # noqa: E501

        :param html_url: The html_url of this ActionWorkflow.  # noqa: E501
        :type: str
        """

        self._html_url = html_url

    @property
    def id(self):
        """Gets the id of this ActionWorkflow.  # noqa: E501

        ID is the unique identifier for the workflow  # noqa: E501

        :return: The id of this ActionWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ActionWorkflow.

        ID is the unique identifier for the workflow  # noqa: E501

        :param id: The id of this ActionWorkflow.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ActionWorkflow.  # noqa: E501

        Name is the name of the workflow  # noqa: E501

        :return: The name of this ActionWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ActionWorkflow.

        Name is the name of the workflow  # noqa: E501

        :param name: The name of this ActionWorkflow.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def path(self):
        """Gets the path of this ActionWorkflow.  # noqa: E501

        Path is the file path of the workflow  # noqa: E501

        :return: The path of this ActionWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ActionWorkflow.

        Path is the file path of the workflow  # noqa: E501

        :param path: The path of this ActionWorkflow.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def state(self):
        """Gets the state of this ActionWorkflow.  # noqa: E501

        State indicates if the workflow is active or disabled  # noqa: E501

        :return: The state of this ActionWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ActionWorkflow.

        State indicates if the workflow is active or disabled  # noqa: E501

        :param state: The state of this ActionWorkflow.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def updated_at(self):
        """Gets the updated_at of this ActionWorkflow.  # noqa: E501


        :return: The updated_at of this ActionWorkflow.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ActionWorkflow.


        :param updated_at: The updated_at of this ActionWorkflow.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def url(self):
        """Gets the url of this ActionWorkflow.  # noqa: E501

        URL is the API URL for this workflow  # noqa: E501

        :return: The url of this ActionWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ActionWorkflow.

        URL is the API URL for this workflow  # noqa: E501

        :param url: The url of this ActionWorkflow.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionWorkflow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionWorkflow):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ActionWorkflow):
            return True

        return self.to_dict() != other.to_dict()
