# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.25.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class ActionWorkflowStep(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'completed_at': 'datetime',
        'conclusion': 'str',
        'name': 'str',
        'number': 'int',
        'started_at': 'datetime',
        'status': 'str'
    }

    attribute_map = {
        'completed_at': 'completed_at',
        'conclusion': 'conclusion',
        'name': 'name',
        'number': 'number',
        'started_at': 'started_at',
        'status': 'status'
    }

    def __init__(self, completed_at=None, conclusion=None, name=None, number=None, started_at=None, status=None, _configuration=None):  # noqa: E501
        """ActionWorkflowStep - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._completed_at = None
        self._conclusion = None
        self._name = None
        self._number = None
        self._started_at = None
        self._status = None
        self.discriminator = None

        if completed_at is not None:
            self.completed_at = completed_at
        if conclusion is not None:
            self.conclusion = conclusion
        if name is not None:
            self.name = name
        if number is not None:
            self.number = number
        if started_at is not None:
            self.started_at = started_at
        if status is not None:
            self.status = status

    @property
    def completed_at(self):
        """Gets the completed_at of this ActionWorkflowStep.  # noqa: E501


        :return: The completed_at of this ActionWorkflowStep.  # noqa: E501
        :rtype: datetime
        """
        return self._completed_at

    @completed_at.setter
    def completed_at(self, completed_at):
        """Sets the completed_at of this ActionWorkflowStep.


        :param completed_at: The completed_at of this ActionWorkflowStep.  # noqa: E501
        :type: datetime
        """

        self._completed_at = completed_at

    @property
    def conclusion(self):
        """Gets the conclusion of this ActionWorkflowStep.  # noqa: E501


        :return: The conclusion of this ActionWorkflowStep.  # noqa: E501
        :rtype: str
        """
        return self._conclusion

    @conclusion.setter
    def conclusion(self, conclusion):
        """Sets the conclusion of this ActionWorkflowStep.


        :param conclusion: The conclusion of this ActionWorkflowStep.  # noqa: E501
        :type: str
        """

        self._conclusion = conclusion

    @property
    def name(self):
        """Gets the name of this ActionWorkflowStep.  # noqa: E501


        :return: The name of this ActionWorkflowStep.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ActionWorkflowStep.


        :param name: The name of this ActionWorkflowStep.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def number(self):
        """Gets the number of this ActionWorkflowStep.  # noqa: E501


        :return: The number of this ActionWorkflowStep.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this ActionWorkflowStep.


        :param number: The number of this ActionWorkflowStep.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def started_at(self):
        """Gets the started_at of this ActionWorkflowStep.  # noqa: E501


        :return: The started_at of this ActionWorkflowStep.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this ActionWorkflowStep.


        :param started_at: The started_at of this ActionWorkflowStep.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def status(self):
        """Gets the status of this ActionWorkflowStep.  # noqa: E501


        :return: The status of this ActionWorkflowStep.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ActionWorkflowStep.


        :param status: The status of this ActionWorkflowStep.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionWorkflowStep, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionWorkflowStep):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ActionWorkflowStep):
            return True

        return self.to_dict() != other.to_dict()
