# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class ActionArtifact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'archive_download_url': 'str',
        'created_at': 'datetime',
        'expired': 'bool',
        'expires_at': 'datetime',
        'id': 'int',
        'name': 'str',
        'size_in_bytes': 'int',
        'updated_at': 'datetime',
        'url': 'str',
        'workflow_run': 'ActionWorkflowRun'
    }

    attribute_map = {
        'archive_download_url': 'archive_download_url',
        'created_at': 'created_at',
        'expired': 'expired',
        'expires_at': 'expires_at',
        'id': 'id',
        'name': 'name',
        'size_in_bytes': 'size_in_bytes',
        'updated_at': 'updated_at',
        'url': 'url',
        'workflow_run': 'workflow_run'
    }

    def __init__(self, archive_download_url=None, created_at=None, expired=None, expires_at=None, id=None, name=None, size_in_bytes=None, updated_at=None, url=None, workflow_run=None, _configuration=None):  # noqa: E501
        """ActionArtifact - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._archive_download_url = None
        self._created_at = None
        self._expired = None
        self._expires_at = None
        self._id = None
        self._name = None
        self._size_in_bytes = None
        self._updated_at = None
        self._url = None
        self._workflow_run = None
        self.discriminator = None

        if archive_download_url is not None:
            self.archive_download_url = archive_download_url
        if created_at is not None:
            self.created_at = created_at
        if expired is not None:
            self.expired = expired
        if expires_at is not None:
            self.expires_at = expires_at
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if size_in_bytes is not None:
            self.size_in_bytes = size_in_bytes
        if updated_at is not None:
            self.updated_at = updated_at
        if url is not None:
            self.url = url
        if workflow_run is not None:
            self.workflow_run = workflow_run

    @property
    def archive_download_url(self):
        """Gets the archive_download_url of this ActionArtifact.  # noqa: E501


        :return: The archive_download_url of this ActionArtifact.  # noqa: E501
        :rtype: str
        """
        return self._archive_download_url

    @archive_download_url.setter
    def archive_download_url(self, archive_download_url):
        """Sets the archive_download_url of this ActionArtifact.


        :param archive_download_url: The archive_download_url of this ActionArtifact.  # noqa: E501
        :type: str
        """

        self._archive_download_url = archive_download_url

    @property
    def created_at(self):
        """Gets the created_at of this ActionArtifact.  # noqa: E501


        :return: The created_at of this ActionArtifact.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ActionArtifact.


        :param created_at: The created_at of this ActionArtifact.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def expired(self):
        """Gets the expired of this ActionArtifact.  # noqa: E501


        :return: The expired of this ActionArtifact.  # noqa: E501
        :rtype: bool
        """
        return self._expired

    @expired.setter
    def expired(self, expired):
        """Sets the expired of this ActionArtifact.


        :param expired: The expired of this ActionArtifact.  # noqa: E501
        :type: bool
        """

        self._expired = expired

    @property
    def expires_at(self):
        """Gets the expires_at of this ActionArtifact.  # noqa: E501


        :return: The expires_at of this ActionArtifact.  # noqa: E501
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this ActionArtifact.


        :param expires_at: The expires_at of this ActionArtifact.  # noqa: E501
        :type: datetime
        """

        self._expires_at = expires_at

    @property
    def id(self):
        """Gets the id of this ActionArtifact.  # noqa: E501


        :return: The id of this ActionArtifact.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ActionArtifact.


        :param id: The id of this ActionArtifact.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ActionArtifact.  # noqa: E501


        :return: The name of this ActionArtifact.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ActionArtifact.


        :param name: The name of this ActionArtifact.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def size_in_bytes(self):
        """Gets the size_in_bytes of this ActionArtifact.  # noqa: E501


        :return: The size_in_bytes of this ActionArtifact.  # noqa: E501
        :rtype: int
        """
        return self._size_in_bytes

    @size_in_bytes.setter
    def size_in_bytes(self, size_in_bytes):
        """Sets the size_in_bytes of this ActionArtifact.


        :param size_in_bytes: The size_in_bytes of this ActionArtifact.  # noqa: E501
        :type: int
        """

        self._size_in_bytes = size_in_bytes

    @property
    def updated_at(self):
        """Gets the updated_at of this ActionArtifact.  # noqa: E501


        :return: The updated_at of this ActionArtifact.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ActionArtifact.


        :param updated_at: The updated_at of this ActionArtifact.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def url(self):
        """Gets the url of this ActionArtifact.  # noqa: E501


        :return: The url of this ActionArtifact.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ActionArtifact.


        :param url: The url of this ActionArtifact.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def workflow_run(self):
        """Gets the workflow_run of this ActionArtifact.  # noqa: E501


        :return: The workflow_run of this ActionArtifact.  # noqa: E501
        :rtype: ActionWorkflowRun
        """
        return self._workflow_run

    @workflow_run.setter
    def workflow_run(self, workflow_run):
        """Sets the workflow_run of this ActionArtifact.


        :param workflow_run: The workflow_run of this ActionArtifact.  # noqa: E501
        :type: ActionWorkflowRun
        """

        self._workflow_run = workflow_run

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionArtifact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionArtifact):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ActionArtifact):
            return True

        return self.to_dict() != other.to_dict()
