# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.25.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class ActionWorkflowRun(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'actor': 'User',
        'completed_at': 'datetime',
        'conclusion': 'str',
        'display_title': 'str',
        'event': 'str',
        'head_branch': 'str',
        'head_repository': 'Repository',
        'head_sha': 'str',
        'html_url': 'str',
        'id': 'int',
        'path': 'str',
        'repository': 'Repository',
        'repository_id': 'int',
        'run_attempt': 'int',
        'run_number': 'int',
        'started_at': 'datetime',
        'status': 'str',
        'trigger_actor': 'User',
        'url': 'str'
    }

    attribute_map = {
        'actor': 'actor',
        'completed_at': 'completed_at',
        'conclusion': 'conclusion',
        'display_title': 'display_title',
        'event': 'event',
        'head_branch': 'head_branch',
        'head_repository': 'head_repository',
        'head_sha': 'head_sha',
        'html_url': 'html_url',
        'id': 'id',
        'path': 'path',
        'repository': 'repository',
        'repository_id': 'repository_id',
        'run_attempt': 'run_attempt',
        'run_number': 'run_number',
        'started_at': 'started_at',
        'status': 'status',
        'trigger_actor': 'trigger_actor',
        'url': 'url'
    }

    def __init__(self, actor=None, completed_at=None, conclusion=None, display_title=None, event=None, head_branch=None, head_repository=None, head_sha=None, html_url=None, id=None, path=None, repository=None, repository_id=None, run_attempt=None, run_number=None, started_at=None, status=None, trigger_actor=None, url=None, _configuration=None):  # noqa: E501
        """ActionWorkflowRun - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._actor = None
        self._completed_at = None
        self._conclusion = None
        self._display_title = None
        self._event = None
        self._head_branch = None
        self._head_repository = None
        self._head_sha = None
        self._html_url = None
        self._id = None
        self._path = None
        self._repository = None
        self._repository_id = None
        self._run_attempt = None
        self._run_number = None
        self._started_at = None
        self._status = None
        self._trigger_actor = None
        self._url = None
        self.discriminator = None

        if actor is not None:
            self.actor = actor
        if completed_at is not None:
            self.completed_at = completed_at
        if conclusion is not None:
            self.conclusion = conclusion
        if display_title is not None:
            self.display_title = display_title
        if event is not None:
            self.event = event
        if head_branch is not None:
            self.head_branch = head_branch
        if head_repository is not None:
            self.head_repository = head_repository
        if head_sha is not None:
            self.head_sha = head_sha
        if html_url is not None:
            self.html_url = html_url
        if id is not None:
            self.id = id
        if path is not None:
            self.path = path
        if repository is not None:
            self.repository = repository
        if repository_id is not None:
            self.repository_id = repository_id
        if run_attempt is not None:
            self.run_attempt = run_attempt
        if run_number is not None:
            self.run_number = run_number
        if started_at is not None:
            self.started_at = started_at
        if status is not None:
            self.status = status
        if trigger_actor is not None:
            self.trigger_actor = trigger_actor
        if url is not None:
            self.url = url

    @property
    def actor(self):
        """Gets the actor of this ActionWorkflowRun.  # noqa: E501


        :return: The actor of this ActionWorkflowRun.  # noqa: E501
        :rtype: User
        """
        return self._actor

    @actor.setter
    def actor(self, actor):
        """Sets the actor of this ActionWorkflowRun.


        :param actor: The actor of this ActionWorkflowRun.  # noqa: E501
        :type: User
        """

        self._actor = actor

    @property
    def completed_at(self):
        """Gets the completed_at of this ActionWorkflowRun.  # noqa: E501


        :return: The completed_at of this ActionWorkflowRun.  # noqa: E501
        :rtype: datetime
        """
        return self._completed_at

    @completed_at.setter
    def completed_at(self, completed_at):
        """Sets the completed_at of this ActionWorkflowRun.


        :param completed_at: The completed_at of this ActionWorkflowRun.  # noqa: E501
        :type: datetime
        """

        self._completed_at = completed_at

    @property
    def conclusion(self):
        """Gets the conclusion of this ActionWorkflowRun.  # noqa: E501


        :return: The conclusion of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._conclusion

    @conclusion.setter
    def conclusion(self, conclusion):
        """Sets the conclusion of this ActionWorkflowRun.


        :param conclusion: The conclusion of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._conclusion = conclusion

    @property
    def display_title(self):
        """Gets the display_title of this ActionWorkflowRun.  # noqa: E501


        :return: The display_title of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._display_title

    @display_title.setter
    def display_title(self, display_title):
        """Sets the display_title of this ActionWorkflowRun.


        :param display_title: The display_title of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._display_title = display_title

    @property
    def event(self):
        """Gets the event of this ActionWorkflowRun.  # noqa: E501


        :return: The event of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this ActionWorkflowRun.


        :param event: The event of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._event = event

    @property
    def head_branch(self):
        """Gets the head_branch of this ActionWorkflowRun.  # noqa: E501


        :return: The head_branch of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._head_branch

    @head_branch.setter
    def head_branch(self, head_branch):
        """Sets the head_branch of this ActionWorkflowRun.


        :param head_branch: The head_branch of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._head_branch = head_branch

    @property
    def head_repository(self):
        """Gets the head_repository of this ActionWorkflowRun.  # noqa: E501


        :return: The head_repository of this ActionWorkflowRun.  # noqa: E501
        :rtype: Repository
        """
        return self._head_repository

    @head_repository.setter
    def head_repository(self, head_repository):
        """Sets the head_repository of this ActionWorkflowRun.


        :param head_repository: The head_repository of this ActionWorkflowRun.  # noqa: E501
        :type: Repository
        """

        self._head_repository = head_repository

    @property
    def head_sha(self):
        """Gets the head_sha of this ActionWorkflowRun.  # noqa: E501


        :return: The head_sha of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._head_sha

    @head_sha.setter
    def head_sha(self, head_sha):
        """Sets the head_sha of this ActionWorkflowRun.


        :param head_sha: The head_sha of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._head_sha = head_sha

    @property
    def html_url(self):
        """Gets the html_url of this ActionWorkflowRun.  # noqa: E501


        :return: The html_url of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._html_url

    @html_url.setter
    def html_url(self, html_url):
        """Sets the html_url of this ActionWorkflowRun.


        :param html_url: The html_url of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._html_url = html_url

    @property
    def id(self):
        """Gets the id of this ActionWorkflowRun.  # noqa: E501


        :return: The id of this ActionWorkflowRun.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ActionWorkflowRun.


        :param id: The id of this ActionWorkflowRun.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def path(self):
        """Gets the path of this ActionWorkflowRun.  # noqa: E501


        :return: The path of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ActionWorkflowRun.


        :param path: The path of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def repository(self):
        """Gets the repository of this ActionWorkflowRun.  # noqa: E501


        :return: The repository of this ActionWorkflowRun.  # noqa: E501
        :rtype: Repository
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """Sets the repository of this ActionWorkflowRun.


        :param repository: The repository of this ActionWorkflowRun.  # noqa: E501
        :type: Repository
        """

        self._repository = repository

    @property
    def repository_id(self):
        """Gets the repository_id of this ActionWorkflowRun.  # noqa: E501


        :return: The repository_id of this ActionWorkflowRun.  # noqa: E501
        :rtype: int
        """
        return self._repository_id

    @repository_id.setter
    def repository_id(self, repository_id):
        """Sets the repository_id of this ActionWorkflowRun.


        :param repository_id: The repository_id of this ActionWorkflowRun.  # noqa: E501
        :type: int
        """

        self._repository_id = repository_id

    @property
    def run_attempt(self):
        """Gets the run_attempt of this ActionWorkflowRun.  # noqa: E501


        :return: The run_attempt of this ActionWorkflowRun.  # noqa: E501
        :rtype: int
        """
        return self._run_attempt

    @run_attempt.setter
    def run_attempt(self, run_attempt):
        """Sets the run_attempt of this ActionWorkflowRun.


        :param run_attempt: The run_attempt of this ActionWorkflowRun.  # noqa: E501
        :type: int
        """

        self._run_attempt = run_attempt

    @property
    def run_number(self):
        """Gets the run_number of this ActionWorkflowRun.  # noqa: E501


        :return: The run_number of this ActionWorkflowRun.  # noqa: E501
        :rtype: int
        """
        return self._run_number

    @run_number.setter
    def run_number(self, run_number):
        """Sets the run_number of this ActionWorkflowRun.


        :param run_number: The run_number of this ActionWorkflowRun.  # noqa: E501
        :type: int
        """

        self._run_number = run_number

    @property
    def started_at(self):
        """Gets the started_at of this ActionWorkflowRun.  # noqa: E501


        :return: The started_at of this ActionWorkflowRun.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this ActionWorkflowRun.


        :param started_at: The started_at of this ActionWorkflowRun.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def status(self):
        """Gets the status of this ActionWorkflowRun.  # noqa: E501


        :return: The status of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ActionWorkflowRun.


        :param status: The status of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def trigger_actor(self):
        """Gets the trigger_actor of this ActionWorkflowRun.  # noqa: E501


        :return: The trigger_actor of this ActionWorkflowRun.  # noqa: E501
        :rtype: User
        """
        return self._trigger_actor

    @trigger_actor.setter
    def trigger_actor(self, trigger_actor):
        """Sets the trigger_actor of this ActionWorkflowRun.


        :param trigger_actor: The trigger_actor of this ActionWorkflowRun.  # noqa: E501
        :type: User
        """

        self._trigger_actor = trigger_actor

    @property
    def url(self):
        """Gets the url of this ActionWorkflowRun.  # noqa: E501


        :return: The url of this ActionWorkflowRun.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ActionWorkflowRun.


        :param url: The url of this ActionWorkflowRun.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionWorkflowRun, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionWorkflowRun):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ActionWorkflowRun):
            return True

        return self.to_dict() != other.to_dict()
