# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class ActionWorkflowJob(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'completed_at': 'datetime',
        'conclusion': 'str',
        'created_at': 'datetime',
        'head_branch': 'str',
        'head_sha': 'str',
        'html_url': 'str',
        'id': 'int',
        'labels': 'list[str]',
        'name': 'str',
        'run_attempt': 'int',
        'run_id': 'int',
        'run_url': 'str',
        'runner_id': 'int',
        'runner_name': 'str',
        'started_at': 'datetime',
        'status': 'str',
        'steps': 'list[ActionWorkflowStep]',
        'url': 'str'
    }

    attribute_map = {
        'completed_at': 'completed_at',
        'conclusion': 'conclusion',
        'created_at': 'created_at',
        'head_branch': 'head_branch',
        'head_sha': 'head_sha',
        'html_url': 'html_url',
        'id': 'id',
        'labels': 'labels',
        'name': 'name',
        'run_attempt': 'run_attempt',
        'run_id': 'run_id',
        'run_url': 'run_url',
        'runner_id': 'runner_id',
        'runner_name': 'runner_name',
        'started_at': 'started_at',
        'status': 'status',
        'steps': 'steps',
        'url': 'url'
    }

    def __init__(self, completed_at=None, conclusion=None, created_at=None, head_branch=None, head_sha=None, html_url=None, id=None, labels=None, name=None, run_attempt=None, run_id=None, run_url=None, runner_id=None, runner_name=None, started_at=None, status=None, steps=None, url=None, _configuration=None):  # noqa: E501
        """ActionWorkflowJob - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._completed_at = None
        self._conclusion = None
        self._created_at = None
        self._head_branch = None
        self._head_sha = None
        self._html_url = None
        self._id = None
        self._labels = None
        self._name = None
        self._run_attempt = None
        self._run_id = None
        self._run_url = None
        self._runner_id = None
        self._runner_name = None
        self._started_at = None
        self._status = None
        self._steps = None
        self._url = None
        self.discriminator = None

        if completed_at is not None:
            self.completed_at = completed_at
        if conclusion is not None:
            self.conclusion = conclusion
        if created_at is not None:
            self.created_at = created_at
        if head_branch is not None:
            self.head_branch = head_branch
        if head_sha is not None:
            self.head_sha = head_sha
        if html_url is not None:
            self.html_url = html_url
        if id is not None:
            self.id = id
        if labels is not None:
            self.labels = labels
        if name is not None:
            self.name = name
        if run_attempt is not None:
            self.run_attempt = run_attempt
        if run_id is not None:
            self.run_id = run_id
        if run_url is not None:
            self.run_url = run_url
        if runner_id is not None:
            self.runner_id = runner_id
        if runner_name is not None:
            self.runner_name = runner_name
        if started_at is not None:
            self.started_at = started_at
        if status is not None:
            self.status = status
        if steps is not None:
            self.steps = steps
        if url is not None:
            self.url = url

    @property
    def completed_at(self):
        """Gets the completed_at of this ActionWorkflowJob.  # noqa: E501


        :return: The completed_at of this ActionWorkflowJob.  # noqa: E501
        :rtype: datetime
        """
        return self._completed_at

    @completed_at.setter
    def completed_at(self, completed_at):
        """Sets the completed_at of this ActionWorkflowJob.


        :param completed_at: The completed_at of this ActionWorkflowJob.  # noqa: E501
        :type: datetime
        """

        self._completed_at = completed_at

    @property
    def conclusion(self):
        """Gets the conclusion of this ActionWorkflowJob.  # noqa: E501


        :return: The conclusion of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._conclusion

    @conclusion.setter
    def conclusion(self, conclusion):
        """Sets the conclusion of this ActionWorkflowJob.


        :param conclusion: The conclusion of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._conclusion = conclusion

    @property
    def created_at(self):
        """Gets the created_at of this ActionWorkflowJob.  # noqa: E501


        :return: The created_at of this ActionWorkflowJob.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ActionWorkflowJob.


        :param created_at: The created_at of this ActionWorkflowJob.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def head_branch(self):
        """Gets the head_branch of this ActionWorkflowJob.  # noqa: E501


        :return: The head_branch of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._head_branch

    @head_branch.setter
    def head_branch(self, head_branch):
        """Sets the head_branch of this ActionWorkflowJob.


        :param head_branch: The head_branch of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._head_branch = head_branch

    @property
    def head_sha(self):
        """Gets the head_sha of this ActionWorkflowJob.  # noqa: E501


        :return: The head_sha of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._head_sha

    @head_sha.setter
    def head_sha(self, head_sha):
        """Sets the head_sha of this ActionWorkflowJob.


        :param head_sha: The head_sha of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._head_sha = head_sha

    @property
    def html_url(self):
        """Gets the html_url of this ActionWorkflowJob.  # noqa: E501


        :return: The html_url of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._html_url

    @html_url.setter
    def html_url(self, html_url):
        """Sets the html_url of this ActionWorkflowJob.


        :param html_url: The html_url of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._html_url = html_url

    @property
    def id(self):
        """Gets the id of this ActionWorkflowJob.  # noqa: E501


        :return: The id of this ActionWorkflowJob.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ActionWorkflowJob.


        :param id: The id of this ActionWorkflowJob.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def labels(self):
        """Gets the labels of this ActionWorkflowJob.  # noqa: E501


        :return: The labels of this ActionWorkflowJob.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this ActionWorkflowJob.


        :param labels: The labels of this ActionWorkflowJob.  # noqa: E501
        :type: list[str]
        """

        self._labels = labels

    @property
    def name(self):
        """Gets the name of this ActionWorkflowJob.  # noqa: E501


        :return: The name of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ActionWorkflowJob.


        :param name: The name of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def run_attempt(self):
        """Gets the run_attempt of this ActionWorkflowJob.  # noqa: E501


        :return: The run_attempt of this ActionWorkflowJob.  # noqa: E501
        :rtype: int
        """
        return self._run_attempt

    @run_attempt.setter
    def run_attempt(self, run_attempt):
        """Sets the run_attempt of this ActionWorkflowJob.


        :param run_attempt: The run_attempt of this ActionWorkflowJob.  # noqa: E501
        :type: int
        """

        self._run_attempt = run_attempt

    @property
    def run_id(self):
        """Gets the run_id of this ActionWorkflowJob.  # noqa: E501


        :return: The run_id of this ActionWorkflowJob.  # noqa: E501
        :rtype: int
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this ActionWorkflowJob.


        :param run_id: The run_id of this ActionWorkflowJob.  # noqa: E501
        :type: int
        """

        self._run_id = run_id

    @property
    def run_url(self):
        """Gets the run_url of this ActionWorkflowJob.  # noqa: E501


        :return: The run_url of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._run_url

    @run_url.setter
    def run_url(self, run_url):
        """Sets the run_url of this ActionWorkflowJob.


        :param run_url: The run_url of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._run_url = run_url

    @property
    def runner_id(self):
        """Gets the runner_id of this ActionWorkflowJob.  # noqa: E501


        :return: The runner_id of this ActionWorkflowJob.  # noqa: E501
        :rtype: int
        """
        return self._runner_id

    @runner_id.setter
    def runner_id(self, runner_id):
        """Sets the runner_id of this ActionWorkflowJob.


        :param runner_id: The runner_id of this ActionWorkflowJob.  # noqa: E501
        :type: int
        """

        self._runner_id = runner_id

    @property
    def runner_name(self):
        """Gets the runner_name of this ActionWorkflowJob.  # noqa: E501


        :return: The runner_name of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._runner_name

    @runner_name.setter
    def runner_name(self, runner_name):
        """Sets the runner_name of this ActionWorkflowJob.


        :param runner_name: The runner_name of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._runner_name = runner_name

    @property
    def started_at(self):
        """Gets the started_at of this ActionWorkflowJob.  # noqa: E501


        :return: The started_at of this ActionWorkflowJob.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this ActionWorkflowJob.


        :param started_at: The started_at of this ActionWorkflowJob.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def status(self):
        """Gets the status of this ActionWorkflowJob.  # noqa: E501


        :return: The status of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ActionWorkflowJob.


        :param status: The status of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def steps(self):
        """Gets the steps of this ActionWorkflowJob.  # noqa: E501


        :return: The steps of this ActionWorkflowJob.  # noqa: E501
        :rtype: list[ActionWorkflowStep]
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """Sets the steps of this ActionWorkflowJob.


        :param steps: The steps of this ActionWorkflowJob.  # noqa: E501
        :type: list[ActionWorkflowStep]
        """

        self._steps = steps

    @property
    def url(self):
        """Gets the url of this ActionWorkflowJob.  # noqa: E501


        :return: The url of this ActionWorkflowJob.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ActionWorkflowJob.


        :param url: The url of this ActionWorkflowJob.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionWorkflowJob, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionWorkflowJob):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ActionWorkflowJob):
            return True

        return self.to_dict() != other.to_dict()
