# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class ActionRunner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'busy': 'bool',
        'disabled': 'bool',
        'ephemeral': 'bool',
        'id': 'int',
        'labels': 'list[ActionRunnerLabel]',
        'name': 'str',
        'status': 'str'
    }

    attribute_map = {
        'busy': 'busy',
        'disabled': 'disabled',
        'ephemeral': 'ephemeral',
        'id': 'id',
        'labels': 'labels',
        'name': 'name',
        'status': 'status'
    }

    def __init__(self, busy=None, disabled=None, ephemeral=None, id=None, labels=None, name=None, status=None, _configuration=None):  # noqa: E501
        """ActionRunner - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._busy = None
        self._disabled = None
        self._ephemeral = None
        self._id = None
        self._labels = None
        self._name = None
        self._status = None
        self.discriminator = None

        if busy is not None:
            self.busy = busy
        if disabled is not None:
            self.disabled = disabled
        if ephemeral is not None:
            self.ephemeral = ephemeral
        if id is not None:
            self.id = id
        if labels is not None:
            self.labels = labels
        if name is not None:
            self.name = name
        if status is not None:
            self.status = status

    @property
    def busy(self):
        """Gets the busy of this ActionRunner.  # noqa: E501


        :return: The busy of this ActionRunner.  # noqa: E501
        :rtype: bool
        """
        return self._busy

    @busy.setter
    def busy(self, busy):
        """Sets the busy of this ActionRunner.


        :param busy: The busy of this ActionRunner.  # noqa: E501
        :type: bool
        """

        self._busy = busy

    @property
    def disabled(self):
        """Gets the disabled of this ActionRunner.  # noqa: E501


        :return: The disabled of this ActionRunner.  # noqa: E501
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this ActionRunner.


        :param disabled: The disabled of this ActionRunner.  # noqa: E501
        :type: bool
        """

        self._disabled = disabled

    @property
    def ephemeral(self):
        """Gets the ephemeral of this ActionRunner.  # noqa: E501


        :return: The ephemeral of this ActionRunner.  # noqa: E501
        :rtype: bool
        """
        return self._ephemeral

    @ephemeral.setter
    def ephemeral(self, ephemeral):
        """Sets the ephemeral of this ActionRunner.


        :param ephemeral: The ephemeral of this ActionRunner.  # noqa: E501
        :type: bool
        """

        self._ephemeral = ephemeral

    @property
    def id(self):
        """Gets the id of this ActionRunner.  # noqa: E501


        :return: The id of this ActionRunner.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ActionRunner.


        :param id: The id of this ActionRunner.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def labels(self):
        """Gets the labels of this ActionRunner.  # noqa: E501


        :return: The labels of this ActionRunner.  # noqa: E501
        :rtype: list[ActionRunnerLabel]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this ActionRunner.


        :param labels: The labels of this ActionRunner.  # noqa: E501
        :type: list[ActionRunnerLabel]
        """

        self._labels = labels

    @property
    def name(self):
        """Gets the name of this ActionRunner.  # noqa: E501


        :return: The name of this ActionRunner.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ActionRunner.


        :param name: The name of this ActionRunner.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this ActionRunner.  # noqa: E501


        :return: The status of this ActionRunner.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ActionRunner.


        :param status: The status of this ActionRunner.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionRunner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionRunner):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ActionRunner):
            return True

        return self.to_dict() != other.to_dict()
