# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class ContentsExtResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dir_contents': 'list[ContentsResponse]',
        'file_contents': 'ContentsResponse'
    }

    attribute_map = {
        'dir_contents': 'dir_contents',
        'file_contents': 'file_contents'
    }

    def __init__(self, dir_contents=None, file_contents=None, _configuration=None):  # noqa: E501
        """ContentsExtResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._dir_contents = None
        self._file_contents = None
        self.discriminator = None

        if dir_contents is not None:
            self.dir_contents = dir_contents
        if file_contents is not None:
            self.file_contents = file_contents

    @property
    def dir_contents(self):
        """Gets the dir_contents of this ContentsExtResponse.  # noqa: E501

        DirContents contains directory listing when the path represents a directory  # noqa: E501

        :return: The dir_contents of this ContentsExtResponse.  # noqa: E501
        :rtype: list[ContentsResponse]
        """
        return self._dir_contents

    @dir_contents.setter
    def dir_contents(self, dir_contents):
        """Sets the dir_contents of this ContentsExtResponse.

        DirContents contains directory listing when the path represents a directory  # noqa: E501

        :param dir_contents: The dir_contents of this ContentsExtResponse.  # noqa: E501
        :type: list[ContentsResponse]
        """

        self._dir_contents = dir_contents

    @property
    def file_contents(self):
        """Gets the file_contents of this ContentsExtResponse.  # noqa: E501


        :return: The file_contents of this ContentsExtResponse.  # noqa: E501
        :rtype: ContentsResponse
        """
        return self._file_contents

    @file_contents.setter
    def file_contents(self, file_contents):
        """Sets the file_contents of this ContentsExtResponse.


        :param file_contents: The file_contents of this ContentsExtResponse.  # noqa: E501
        :type: ContentsResponse
        """

        self._file_contents = file_contents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContentsExtResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContentsExtResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContentsExtResponse):
            return True

        return self.to_dict() != other.to_dict()
