# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.25.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class CreateActionWorkflowDispatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'inputs': 'dict(str, str)',
        'ref': 'str'
    }

    attribute_map = {
        'inputs': 'inputs',
        'ref': 'ref'
    }

    def __init__(self, inputs=None, ref=None, _configuration=None):  # noqa: E501
        """CreateActionWorkflowDispatch - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._inputs = None
        self._ref = None
        self.discriminator = None

        if inputs is not None:
            self.inputs = inputs
        self.ref = ref

    @property
    def inputs(self):
        """Gets the inputs of this CreateActionWorkflowDispatch.  # noqa: E501


        :return: The inputs of this CreateActionWorkflowDispatch.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this CreateActionWorkflowDispatch.


        :param inputs: The inputs of this CreateActionWorkflowDispatch.  # noqa: E501
        :type: dict(str, str)
        """

        self._inputs = inputs

    @property
    def ref(self):
        """Gets the ref of this CreateActionWorkflowDispatch.  # noqa: E501


        :return: The ref of this CreateActionWorkflowDispatch.  # noqa: E501
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this CreateActionWorkflowDispatch.


        :param ref: The ref of this CreateActionWorkflowDispatch.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and ref is None:
            raise ValueError("Invalid value for `ref`, must not be `None`")  # noqa: E501

        self._ref = ref

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateActionWorkflowDispatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateActionWorkflowDispatch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateActionWorkflowDispatch):
            return True

        return self.to_dict() != other.to_dict()
