# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class MergeUpstreamRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'branch': 'str',
        'ff_only': 'bool'
    }

    attribute_map = {
        'branch': 'branch',
        'ff_only': 'ff_only'
    }

    def __init__(self, branch=None, ff_only=None, _configuration=None):  # noqa: E501
        """MergeUpstreamRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._branch = None
        self._ff_only = None
        self.discriminator = None

        if branch is not None:
            self.branch = branch
        if ff_only is not None:
            self.ff_only = ff_only

    @property
    def branch(self):
        """Gets the branch of this MergeUpstreamRequest.  # noqa: E501


        :return: The branch of this MergeUpstreamRequest.  # noqa: E501
        :rtype: str
        """
        return self._branch

    @branch.setter
    def branch(self, branch):
        """Sets the branch of this MergeUpstreamRequest.


        :param branch: The branch of this MergeUpstreamRequest.  # noqa: E501
        :type: str
        """

        self._branch = branch

    @property
    def ff_only(self):
        """Gets the ff_only of this MergeUpstreamRequest.  # noqa: E501


        :return: The ff_only of this MergeUpstreamRequest.  # noqa: E501
        :rtype: bool
        """
        return self._ff_only

    @ff_only.setter
    def ff_only(self, ff_only):
        """Sets the ff_only of this MergeUpstreamRequest.


        :param ff_only: The ff_only of this MergeUpstreamRequest.  # noqa: E501
        :type: bool
        """

        self._ff_only = ff_only

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MergeUpstreamRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MergeUpstreamRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MergeUpstreamRequest):
            return True

        return self.to_dict() != other.to_dict()
