# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class RunDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'html_url': 'str',
        'run_url': 'str',
        'workflow_run_id': 'int'
    }

    attribute_map = {
        'html_url': 'html_url',
        'run_url': 'run_url',
        'workflow_run_id': 'workflow_run_id'
    }

    def __init__(self, html_url=None, run_url=None, workflow_run_id=None, _configuration=None):  # noqa: E501
        """RunDetails - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._html_url = None
        self._run_url = None
        self._workflow_run_id = None
        self.discriminator = None

        if html_url is not None:
            self.html_url = html_url
        if run_url is not None:
            self.run_url = run_url
        if workflow_run_id is not None:
            self.workflow_run_id = workflow_run_id

    @property
    def html_url(self):
        """Gets the html_url of this RunDetails.  # noqa: E501


        :return: The html_url of this RunDetails.  # noqa: E501
        :rtype: str
        """
        return self._html_url

    @html_url.setter
    def html_url(self, html_url):
        """Sets the html_url of this RunDetails.


        :param html_url: The html_url of this RunDetails.  # noqa: E501
        :type: str
        """

        self._html_url = html_url

    @property
    def run_url(self):
        """Gets the run_url of this RunDetails.  # noqa: E501


        :return: The run_url of this RunDetails.  # noqa: E501
        :rtype: str
        """
        return self._run_url

    @run_url.setter
    def run_url(self, run_url):
        """Sets the run_url of this RunDetails.


        :param run_url: The run_url of this RunDetails.  # noqa: E501
        :type: str
        """

        self._run_url = run_url

    @property
    def workflow_run_id(self):
        """Gets the workflow_run_id of this RunDetails.  # noqa: E501


        :return: The workflow_run_id of this RunDetails.  # noqa: E501
        :rtype: int
        """
        return self._workflow_run_id

    @workflow_run_id.setter
    def workflow_run_id(self, workflow_run_id):
        """Sets the workflow_run_id of this RunDetails.


        :param workflow_run_id: The workflow_run_id of this RunDetails.  # noqa: E501
        :type: int
        """

        self._workflow_run_id = workflow_run_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RunDetails):
            return True

        return self.to_dict() != other.to_dict()
