# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from giteapy.configuration import Configuration


class UpdateBranchRepoOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'force': 'bool',
        'new_commit_id': 'str',
        'old_commit_id': 'str'
    }

    attribute_map = {
        'force': 'force',
        'new_commit_id': 'new_commit_id',
        'old_commit_id': 'old_commit_id'
    }

    def __init__(self, force=None, new_commit_id=None, old_commit_id=None, _configuration=None):  # noqa: E501
        """UpdateBranchRepoOption - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._force = None
        self._new_commit_id = None
        self._old_commit_id = None
        self.discriminator = None

        if force is not None:
            self.force = force
        self.new_commit_id = new_commit_id
        if old_commit_id is not None:
            self.old_commit_id = old_commit_id

    @property
    def force(self):
        """Gets the force of this UpdateBranchRepoOption.  # noqa: E501

        Force update even if the change is not a fast-forward  # noqa: E501

        :return: The force of this UpdateBranchRepoOption.  # noqa: E501
        :rtype: bool
        """
        return self._force

    @force.setter
    def force(self, force):
        """Sets the force of this UpdateBranchRepoOption.

        Force update even if the change is not a fast-forward  # noqa: E501

        :param force: The force of this UpdateBranchRepoOption.  # noqa: E501
        :type: bool
        """

        self._force = force

    @property
    def new_commit_id(self):
        """Gets the new_commit_id of this UpdateBranchRepoOption.  # noqa: E501

        New commit SHA (or any ref) the branch should point to  # noqa: E501

        :return: The new_commit_id of this UpdateBranchRepoOption.  # noqa: E501
        :rtype: str
        """
        return self._new_commit_id

    @new_commit_id.setter
    def new_commit_id(self, new_commit_id):
        """Sets the new_commit_id of this UpdateBranchRepoOption.

        New commit SHA (or any ref) the branch should point to  # noqa: E501

        :param new_commit_id: The new_commit_id of this UpdateBranchRepoOption.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and new_commit_id is None:
            raise ValueError("Invalid value for `new_commit_id`, must not be `None`")  # noqa: E501

        self._new_commit_id = new_commit_id

    @property
    def old_commit_id(self):
        """Gets the old_commit_id of this UpdateBranchRepoOption.  # noqa: E501

        Expected old commit SHA of the branch; if provided it must match the current tip  # noqa: E501

        :return: The old_commit_id of this UpdateBranchRepoOption.  # noqa: E501
        :rtype: str
        """
        return self._old_commit_id

    @old_commit_id.setter
    def old_commit_id(self, old_commit_id):
        """Sets the old_commit_id of this UpdateBranchRepoOption.

        Expected old commit SHA of the branch; if provided it must match the current tip  # noqa: E501

        :param old_commit_id: The old_commit_id of this UpdateBranchRepoOption.  # noqa: E501
        :type: str
        """

        self._old_commit_id = old_commit_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateBranchRepoOption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateBranchRepoOption):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateBranchRepoOption):
            return True

        return self.to_dict() != other.to_dict()
